linux_task:
  container:
    image: aquova/songbird:1.0

  build_script:
    - make gui

  songbird_artifacts:
    path: gui/target/release/songbird_gui

osx_task:
  osx_instance:
    image: catalina-base

  setup_script:
    - brew update
    - brew install rust

  build_script:
    - make gui

  songbird_artifacts:
    path: gui/target/release/songbird_gui

win_task:
  container:
    image: aquova/songbird:1.0

  build_script:
    - make windows

  songbird_artifacts:
    path: gui/target/x86_64-pc-windows-gnu/release/songbird_gui.exe

wasm_task:
  container:
    image: aquova/songbird:1.0

  build_script:
    - make wasm

  package_script:
    - zip -r songbird_wasm.zip web

  songbird_artifacts:
    path: songbird_wasm.zip
