linux_task:
  container:
    image: rust:latest

  setup_script:
    - apt-get update
    - apt-get -y install libsdl2-dev zip

  build_script:
    - make sdl

  package_script:
    - mkdir -p songbird/assets
    - cp sdl/assets/icon_purple.png songbird/assets
    - cp sdl/target/debug/songbird_sdl songbird/songbird
    - zip -r songbird_linux.zip songbird

  songbird_artifacts:
    path: songbird_linux.zip

osx_task:
  osx_instance:
    image: catalina-base

  setup_script:
    - brew update
    - brew install rust sdl2

  build_script:
    - make sdl

  package_script:
    - mkdir -p songbird/assets
    - cp sdl/assets/icon_purple.png songbird/assets
    - cp sdl/target/debug/songbird_sdl songbird/songbird
    - zip -r songbird_mac.zip songbird

  songbird_artifacts:
    path: songbird_mac.zip

win_task:
  container:
    image: rust:1.44.0

  setup_script:
    - apt-get update
    - apt-get -y install libsdl2-dev zip gcc-mingw-w64-x86-64
    # This is from sdl/setup_win.sh
    - rustup target add x86_64-pc-windows-gnu
    - cp -r sdl/lib/SDL2-2.0.12/x86_64-w64-mingw32/lib/* $RUSTUP_HOME/toolchains/1.44.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib
    - cp sdl/lib/SDL2-2.0.12/x86_64-w64-mingw32/bin/SDL2.dll sdl

  build_script:
    - make windows

  package_script:
    - mkdir -p songbird/assets
    - cp sdl/assets/icon_purple.png songbird/assets
    - cp sdl/*.dll songbird
    - cp sdl/songbird_sdl.exe songbird/songbird.exe
    - zip -r songbird_win.zip songbird

  songbird_artifacts:
    path: songbird_win.zip

wasm_task:
  container:
    image: rust:latest

  setup_script:
    - apt-get update
    - apt-get -y install zip
    # Install wasm-pack
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

  build_script:
    - make wasm

  package_script:
    - zip -r songbird_wasm.zip web

  songbird_artifacts:
    path: songbird_wasm.zip
