linux_task:
  container:
    image: rust:latest

  setup_script:
    - apt-get update
    - apt-get -y install libsdl2-dev libsdl2-image-dev zip

  build_script:
    - make sdl

  package_script:
    - mkdir -p agba/assets
    - cp sdl/assets/icon_purple.png agba/assets
    - cp sdl/target/debug/agba_sdl agba/agba
    - zip -r agba_linux.zip agba

  agba_artifacts:
    path: agba_linux.zip

osx_task:
  osx_instance:
    image: catalina-base

  setup_script:
    - brew update
    - brew install rust sdl2 sdl2_image

  build_script:
    - make sdl

  package_script:
    - mkdir -p agba/assets
    - cp sdl/assets/icon_purple.png agba/assets
    - cp sdl/target/debug/agba_sdl agba/agba
    - zip -r agba_mac.zip agba

  agba_artifacts:
    path: agba_mac.zip

wasm_task:
  container:
    image: rust:latest

  setup_script:
    - apt-get update
    - apt-get -y install zip
    # Install wasm-pack
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

  build_script:
    - make wasm

  package_script:
    - zip -r agba_wasm.zip web

  agba_artifacts:
    path: agba_wasm.zip
