linux_task:
  container:
    image: rust:latest

  setup_script:
    - apt-get update
    - apt-get -y install cmake

  build_script:
    - make sdl

  songbird_artifacts:
    path: sdl/target/release/songbird_sdl

osx_task:
  osx_instance:
    image: catalina-base

  setup_script:
    - brew update
    - brew install rust cmake sdl2

  build_script:
    - make sdl

  songbird_artifacts:
    path: sdl/target/release/songbird_sdl

win_task:
  container:
    image: rust:1.44.0

  setup_script:
    - apt-get update
    - apt-get -y install cmake gcc-mingw-w64-x86-64
    - rustup target add x86_64-pc-windows-gnu

  build_script:
    - make windows

  songbird_artifacts:
    path: sdl/songbird_sdl.exe

wasm_task:
  container:
    image: rust:latest

  setup_script:
    - apt-get update
    - apt-get -y install zip
    # Install wasm-pack
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

  build_script:
    - make wasm

  package_script:
    - zip -r songbird_wasm.zip web

  songbird_artifacts:
    path: songbird_wasm.zip
