[package]
name = "agba"
version = "0.1.0"
authors = ["aquova <abrick912@gmail.com>"]
edition = "2018"

[dependencies]
gb_core = { path = "core" }
sdl2 = { version = "^0.32.2", features = [ "image" ] }
# sdl2 = "^0.32.2"
