[package]
name = "agba_sdl"
version = "0.1.0"
authors = ["aquova <abrick912@gmail.com>"]
edition = "2018"

[dependencies]
agba_core = { path = "../core" }
sdl2 = { version = "^0.32.2", features = [ "image" ] }
