[package]
name = "agba_wasm"
version = "0.1.0"
authors = ["aquova <abrick912@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.22"
agba_core = { path = "../core" }

[lib]
crate-type = ["cdylib"]
